[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/newsletter-introduction"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/updates"
  [headers.values]
    Content-Type = "application/json"