[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/intro"
  [headers.values]
    Content-Type = "application/json"